import type {
  Currency,
  GameLeaderboard,
  Player,
  Transaction,
} from "@/types/types";
import {
  // refactory
  ChartBarIncreasing,
  Gamepad2,
  Gift,
  History,
  Medal,
  Settings,
  UserPlus,
  Wallet,
  Home,
} from "lucide-react";

export const navItems = [
  { icon: Home, label: "PlayZa", path: "/", mobile: true },
  { icon: Gamepad2, label: "Games", path: "/games", mobile: true },
  { icon: Medal, label: "Tournaments", path: "/tournaments" },
  {
    icon: ChartBarIncreasing,
    label: "Leaderboard",
    path: "/leaderboard",
    mobile: true,
  },
  { icon: Gift, label: "Bonus", path: "/bonus" },
  { icon: UserPlus, label: "Referral", path: "/referral" },
  { icon: Wallet, label: "Wallet", path: "/wallet", mobile: true },
  { icon: History, label: "History", path: "/history" },
  { icon: Settings, label: "Settings", path: "/settings", mobile: true },
];

export const winners = [
  {
    id: 1,
    username: "ProGamerX",
    game: "Speed Math Clash",
    amountWon: 25000,
    wonAt: "2026-02-17T09:15:00Z",
  },
  {
    id: 2,
    username: "NaijaSharp",
    game: "Quick Trivia Battle",
    amountWon: 18000,
    wonAt: "2026-02-17T08:40:00Z",
  },
  {
    id: 3,
    username: "BrainBoss",
    game: "Word Arena",
    amountWon: 32000,
    wonAt: "2026-02-17T07:55:00Z",
  },
  {
    id: 4,
    username: "FastFinger",
    game: "Reaction Rush",
    amountWon: 12000,
    wonAt: "2026-02-17T07:10:00Z",
  },
  {
    id: 5,
    username: "ClutchKing",
    game: "Sudden Death Quiz",
    amountWon: 45000,
    wonAt: "2026-02-16T21:30:00Z",
  },
  {
    id: 6,
    username: "AcePlayer",
    game: "Memory Grid",
    amountWon: 15000,
    wonAt: "2026-02-16T20:45:00Z",
  },
  {
    id: 7,
    username: "VictoryVibes",
    game: "Battle IQ",
    amountWon: 28000,
    wonAt: "2026-02-16T19:20:00Z",
  },
  {
    id: 8,
    username: "SharpMind",
    game: "Rapid Fire Trivia",
    amountWon: 17000,
    wonAt: "2026-02-16T18:05:00Z",
  },
  {
    id: 9,
    username: "GameLord",
    game: "Strategy Showdown",
    amountWon: 52000,
    wonAt: "2026-02-16T16:50:00Z",
  },
  {
    id: 10,
    username: "EliteSniper",
    game: "Precision Play",
    amountWon: 21000,
    wonAt: "2026-02-16T15:30:00Z",
  },
  {
    id: 11,
    username: "MindBlazer",
    game: "Ultimate Quiz Arena",
    amountWon: 39000,
    wonAt: "2026-02-16T14:10:00Z",
  },
  {
    id: 12,
    username: "SwiftStrike",
    game: "Lightning Round",
    amountWon: 14000,
    wonAt: "2026-02-16T12:55:00Z",
  },
  {
    id: 13,
    username: "ArenaKing",
    game: "Champions Gauntlet",
    amountWon: 60000,
    wonAt: "2026-02-16T11:40:00Z",
  },
  {
    id: 14,
    username: "QuizTitan",
    game: "Knowledge Knockout",
    amountWon: 26000,
    wonAt: "2026-02-16T10:25:00Z",
  },
  {
    id: 15,
    username: "SkillMaster",
    game: "Logic Duel",
    amountWon: 23000,
    wonAt: "2026-02-16T09:05:00Z",
  },
];

export const badgeStyles = {
  HOT: " text-red-600",
  NEW: "text-purple-400",
};

export const players: Player[] = [
  {
    id: crypto.randomUUID(),
    username: "ShadowX",
    avatar: "https://i.pravatar.cc/150?img=1",
    score: 2100,
    status: "playing",
    rank: 1,
    kills: 16,
    level: 35,
    team: "Red",
    ping: 24,
    country: "Nigeria",
    joinedAt: "2026-02-22T14:01:10Z",
    isHost: true,
  },
  {
    id: crypto.randomUUID(),
    username: "NovaStrike",
    avatar: "https://i.pravatar.cc/150?img=2",
    score: 1980,
    status: "playing",
    rank: 2,
    kills: 14,
    level: 31,
    team: "Blue",
    ping: 30,
    country: "Ghana",
    joinedAt: "2026-02-22T14:02:03Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "BlazeHunter",
    avatar: "https://i.pravatar.cc/150?img=3",
    score: 1855,
    status: "playing",
    rank: 3,
    kills: 12,
    level: 29,
    team: "Red",
    ping: 34,
    country: "Kenya",
    joinedAt: "2026-02-22T14:02:45Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "FrostByte",
    avatar: "https://i.pravatar.cc/150?img=4",
    score: 1702,
    status: "playing",
    rank: 4,
    kills: 11,
    level: 27,
    team: "Blue",
    ping: 41,
    country: "UK",
    joinedAt: "2026-02-22T14:03:12Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "StormRider",
    avatar: "https://i.pravatar.cc/150?img=5",
    score: 1590,
    status: "playing",
    rank: 5,
    kills: 9,
    level: 25,
    team: "Red",
    ping: 38,
    country: "USA",
    joinedAt: "2026-02-22T14:03:40Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "NightPulse",
    avatar: "https://i.pravatar.cc/150?img=6",
    score: 1480,
    status: "playing",
    rank: 6,
    kills: 8,
    level: 23,
    team: "Blue",
    ping: 44,
    country: "Canada",
    joinedAt: "2026-02-22T14:04:01Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "QuantumAce",
    avatar: "https://i.pravatar.cc/150?img=7",
    score: 1320,
    status: "playing",
    rank: 7,
    kills: 7,
    level: 21,
    team: "Red",
    ping: 52,
    country: "Germany",
    joinedAt: "2026-02-22T14:04:20Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "EchoBlade",
    avatar: "https://i.pravatar.cc/150?img=8",
    score: 1210,
    status: "playing",
    rank: 8,
    kills: 6,
    level: 20,
    team: "Blue",
    ping: 49,
    country: "Nigeria",
    joinedAt: "2026-02-22T14:04:52Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "IronPhantom",
    avatar: "https://i.pravatar.cc/150?img=9",
    score: 1105,
    status: "playing",
    rank: 9,
    kills: 5,
    level: 18,
    team: "Red",
    ping: 57,
    country: "South Africa",
    joinedAt: "2026-02-22T14:05:13Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "RapidVortex",
    avatar: "https://i.pravatar.cc/150?img=10",
    score: 980,
    status: "playing",
    rank: 10,
    kills: 4,
    level: 17,
    team: "Blue",
    ping: 60,
    country: "India",
    joinedAt: "2026-02-22T14:05:40Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "CyberKnight",
    avatar: "https://i.pravatar.cc/150?img=11",
    score: 860,
    status: "eliminated",
    rank: 11,
    kills: 3,
    level: 16,
    team: "Red",
    ping: 63,
    country: "Brazil",
    joinedAt: "2026-02-22T14:06:02Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "PixelSniper",
    avatar: "https://i.pravatar.cc/150?img=12",
    score: 740,
    status: "eliminated",
    rank: 12,
    kills: 3,
    level: 15,
    team: "Blue",
    ping: 71,
    country: "France",
    joinedAt: "2026-02-22T14:06:24Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "GhostRunner",
    avatar: "https://i.pravatar.cc/150?img=13",
    score: 600,
    status: "ended",
    rank: 13,
    kills: 2,
    level: 14,
    team: "Red",
    ping: 80,
    country: "Spain",
    joinedAt: "2026-02-22T14:06:50Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "NeonDrift",
    avatar: "https://i.pravatar.cc/150?img=14",
    score: 420,
    status: "disconnected",
    rank: 14,
    kills: 1,
    level: 13,
    team: "Blue",
    ping: 120,
    country: "Italy",
    joinedAt: "2026-02-22T14:07:10Z",
    isHost: false,
  },
  {
    id: crypto.randomUUID(),
    username: "ZenArcade",
    avatar: "https://i.pravatar.cc/150?img=15",
    score: 0,
    status: "waiting",
    rank: 15,
    kills: 0,
    level: 12,
    team: "Red",
    ping: 29,
    country: "Nigeria",
    joinedAt: "2026-02-22T14:07:35Z",
    isHost: false,
  },
];

export const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
] as const;

export const DAYS_OF_WEEK = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
] as const;

export const gameSession = [
  {
    id: "sess_morning_001",
    name: "Morning Rush",
    start: "08:00",
    end: "11:00",
    status: "live",
    entries: 145,
    prizePool: 14500,
    topScore: 9850,
    topPlayer: "KingOfSpeed",
  },
  {
    id: "sess_afternoon_001",
    name: "Afternoon Grind",
    start: "15:00",
    end: "18:00",
    status: "upcoming",
    entries: 0,
    prizePool: 0,
    topScore: 0,
    topPlayer: null,
  },
  {
    id: "sess_evening_001",
    name: "Night Owl",
    start: "20:00",
    end: "23:00",
    status: "upcoming",
    entries: 0,
    prizePool: 0,
    topScore: 0,
    topPlayer: null,
  },
];

import { GiMedal } from "react-icons/gi";
import { BiMedal, BiStar } from "react-icons/bi";

export const statsCards = [
  {
    id: "score",
    title: "Your Score",
    value: "1,450",
    valueColor: "text-white",
    icon: GiMedal,
  },
  {
    id: "rank",
    title: "Your Rank",
    value: "#12",
    valueColor: "text-primary",
    icon: BiMedal,
  },
  {
    id: "best-score",
    title: "Best Score",
    value: "1,820",
    valueColor: "text-white",
    icon: BiStar,
  },
  {
    id: "entries",
    title: "Entries Used",
    value: "5",
    subValue: "/ 10",
    progress: 50,
  },
  {
    id: "spent",
    title: "Total Spent",
    value: "$25.00",
    valueColor: "text-white",
  },
  {
    id: "behind",
    title: "Behind Rank 1",
    value: "210",
    valueColor: "text-red-400",
    trend: "up",
  },
];

export const leaderboardTop = [
  { rank: 1, name: "Alex Thunder", points: 12450, avatar: "AT" },
  { rank: 2, name: "Sarah Chen", points: 11820, avatar: "SC" },
  { rank: 3, name: "Marcus Rey", points: 10990, avatar: "MR" },
];


export const currencies: Currency[] = [
  { code: "NGN", symbol: "₦", rate: 100, flag: "🇳🇬" },
  { code: "USD", symbol: "$", rate: 0.067, flag: "🇺🇸" },
  { code: "EUR", symbol: "€", rate: 0.061, flag: "🇪🇺" },
  { code: "GBP", symbol: "£", rate: 0.052, flag: "🇬🇧" },
  { code: "GHS", symbol: "₵", rate: 1.13, flag: "🇬🇭" },
  { code: "KES", symbol: "KSh", rate: 8.66, flag: "🇰🇪" },
  { code: "ZAR", symbol: "R", rate: 1.22, flag: "🇿🇦" },
];

// Stats
export const stats = [
  { label: "Games Played", value: "48", icon: "🎮" },
  { label: "Total Wins", value: "32", icon: "🏆" },
  { label: "Win Rate", value: "66%", icon: "📊" },
];
